# -*- encoding: utf-8 -*-

"""
Command-Line Interface to Manage LLM Essential Function Code(s)
===============================================================

Module's command-line utility tool to manage essential functions that
are being regularly used by LLM tools for fine control and refine the
content generated by LLM models. The command line is developed using
:mod:`argparse` which is a standard Python package.

.. code-block:: shell

    $ pip install polyskills
    $ polyskills --help # show help documentation

The CLI tool is developed to manage LLM essential functions - like
``SKILLS.md``, ``AGENTS.md`` etc. required to refine the contents.
"""

import sys
import argparse

from pathlib import Path
from typing import Callable, Optional

from polyskills.apps.tools import SupportedTools
from polyskills.remote.sources import (
    GithubManager, SourceControl, SourceManager, ValidSources
)

# ? registry mapping each supported remote enumeration to its concrete
# ? :class:`SourceManager` factory; extending the framework with a new
# ? remote provider only requires registering the pair below.
_SOURCE_MANAGERS = {
    ValidSources.GITHUB : GithubManager,
}


def buildParser() -> argparse.ArgumentParser:
    """
    Constructs the :func:`argparse.parser` for the :mod:`polyskills`
    CLI tools, that provides sub-parsers with required mutually
    exclusive groups for library management from remote sources.
    """

    parser = argparse.ArgumentParser(
        prog = "polyskills", description = (
            "Manage portable extensions (like skills, agents, etc.) "
            "hosted on any source controlled remote repository for "
            "LLM tools (like Claude Code, CodeX); across different "
            "project environments or system. The extensions are "
            "useful in providing context that improve the output "
            "of a LLM model. Use one of the available commands; and "
            "to check the command documentation use '--help' flag."
        )
    )

    subparser = parser.add_subparsers(
        dest = "command", required = True, metavar = "COMMAND"
    )

    # ? Creating Subparsers:: SOURCES - List Available Sources
    tools = subparser.add_parser(
        "tools", help = (
            "List the supported tools which either accepts agents "
            "skills (https://agentskills.io/home) file, or a converter "
            "is available to generate prompt. For example, tools like "
            "Claude Code is built to accept the 'SKILLS.md' or an "
            "'AGENTS.md' file, while CodeX requires a system prompt. "
            "The manager accepts argument to set the tool name so "
            "that the content from the remote is safely converted. "
            "The terminal exists after supported list display."
        )
    )
    tools.set_defaults(
        func = lambda : None # TODO
    )

    # ? Creating Subparsers:: SOURCES - List Available Sources
    sources = subparser.add_parser(
        "sources", help = (
            "List the available (or supported) remote sources, and exit."
        )
    )
    sources.set_defaults(
        func = lambda : "Available Sources:\n" + "\t".join([
            f"\t>> {str(idx + 1).zfill(2)}. {mem.name} - {mem.value}"
            for idx, mem in enumerate(ValidSources)
        ])
    )

    # ? Creating Subparsers:: LIST - Enumerate Library Contents
    listing = subparser.add_parser(
        "list", help = (
            "List the available extensions (skills, agents, etc.) "
            "hosted under the source directory of a remote repository "
            "without downloading any content. Useful to discover the "
            "valid '--name' values for the 'manager' command."
        )
    )

    listing.add_argument(
        "remote", help = (
            "Remote URL for the Skills Repository, e.g., "
            "https://github.com/<owner>/<repository>. Check the list "
            "of supported remote sources using 'polyskills sources'."
        )
    )

    listing.add_argument(
        "--pagination", metavar = "[100]", type = int, default = 100,
        help = (
            "Pagination parameter forwarded to the underlying REST "
            "API client. Defaults to 100."
        )
    )

    listing.add_argument(
        "--token", type = str, help = (
            "Authentication token for private/self-hosted remotes. "
            "Overridden by the 'POLYSKILLS_REMOTE_TOKEN' environment "
            "variable when set."
        )
    )

    listing.add_argument(
        "--version", type = str, default = "master", metavar = "[master]",
        help = (
            "Exact version (a tag or a commit SHA) at which to list "
            "the extensions, defaults to 'master'."
        )
    )

    listing.add_argument(
        "-s", "--source", type = str, default = None, metavar = "",
        help = (
            "Source directory to enumerate, defaults to './skills' "
            "for the 'skills' library, './agents' for 'agents', etc."
        )
    )

    listing_libraries = listing.add_subparsers(
        dest = "library", required = True, metavar = "LIBRARY", help = (
            "Library type to enumerate (skills, agents, etc.)."
        )
    )

    listing_libraries.add_parser(
        "skills", help = "List the available skills on the remote."
    )
    listing_libraries.add_parser(
        "agents", help = "List the available agents on the remote."
    )

    # ? Creating Subparsers:: MANAGE - Manage Remote Library
    manager = subparser.add_parser(
        "manager", help = (
            "Main method to manage skills, agents, etc. for a LLM "
            "tool, from remote sources, i.e., to fetch and/or update "
            "the library content in different projects or systems. "
            "Check 'polyskills manage --help' for more details."
        )
    )

    manager.add_argument(
        "remote", help = (
            "Remote URL for the Skills Repository, e.g., "
            "https://github.com/<owner>/<repository>. Check the list "
            "of supported remote sources using 'polyskills sources'."
        )
    )

    manager.add_argument(
        "--pagination", metavar = "[100]", type = int,
        default = 100, help = (
            "Set the pagination parameter that controls how many "
            "requests are returned for a 'GET' from the REST API "
            "endpoints, example 'https://api.github.com/repos/...' "
            "which is the endpoint for GitHub."
        )
    )

    manager.add_argument(
        "--token", type = str, help = (
            "Authentication token (typically required for a private "
            "or a self-hosted repository) that is additionally "
            "required for validation. It is recommended not to use "
            "the security token in production system and should only "
            "be used in a testing environment. The token parameter "
            "has a lower precedency and is over written by using an "
            "environment variable 'POLYSKILLS_REMOTE_TOKEN' value."
        )
    )

    # ? directory control for the manager/library
    # ? extension selectors shared across every library sub-command
    manager.add_argument(
        "-n", "--name", type = str, required = True, metavar = "", help = (
            "Name of the extension to fetch from the remote source, "
            "e.g., 'sql-code-format'. The value is the leaf directory "
            "name on the remote under the resolved source directory "
            "(see '--source')."
        )
    )

    manager.add_argument(
        "--version", type = str, default = "master", metavar = "[master]",
        help = (
            "Exact version (a tag or a commit SHA) of the extension to "
            "fetch, defaults to 'master' which resolves to the latest "
            "content on the default branch of the remote repository."
        )
    )

    manager.add_argument(
        "--exists", type = str, default = "fail",
        choices = ("fail", "overwrite", "merge"), help = (
            "Behavior when the destination directory already exists "
            "and is non-empty. 'fail' raises an error, 'overwrite' "
            "removes and recreates the destination, and 'merge' "
            "extracts on top of the existing tree (overwrites on "
            "conflict). Defaults to 'fail'."
        )
    )

    manager.add_argument(
        "-s", "--source", type = str, default = None,
        metavar = "", help = (
            "Source directory for the remote from which the extension "
            "is fetched, defaults to ./skills for `--library skills` "
            "mode or ./agents for `--library agents` mode, etc. as "
            "per the Agents Skills [https://agentskills.io/home] "
            "standards."
        )
    )

    manager.add_argument(
        "-d", "--destination", type = str, default = None,
        metavar = "", help = (
            "Destination directory into which the extension is to be "
            "placed, this defaults to the local directory into their "
            "respective directories like ./skills, ./agents, etc. "
            "as per the standards."
        )
    )

    # ? Create a Sub-Parser for the ``manager`` Parser for Libraries
    # ? {``skills``, ``agents``, ...} for different actions
    libraries = manager.add_subparsers(
        dest = "library", required = True, metavar = "LIBRARY", help = (
            "Mode to fetch different types of libraries (skills, "
            "agents, etc.) for different requirements from remote."
        )
    )

    skills = libraries.add_parser(
        "skills", help = (
            "A sub-parser endpoint to manage skills for an LLM Tool. "
            "Typically, the function fetches an 'SKILL.md' file (if "
            "Agents Skills [https://agentskills.io/home]) is supported "
            "else the skill is converted to a prompt. Check the "
            "list of supported LLM tools using 'polyskills tools' "
            "for more details."
        )
    )

    agents = libraries.add_parser(
        "agents", help = (
            "A sub-parser endpoint to manage agents for an LLM Tool. "
            "Typically, the function fetches an 'AGENTS.md' file and "
            "registers the agent definition with the target LLM tool. "
            "Check the list of supported LLM tools using "
            "'polyskills tools' for more details."
        )
    )

    return parser


def _resolveManager(
    remote : str, control : SourceControl
) -> SourceManager:
    """
    Detect which :class:`ValidSources` provider hosts ``remote`` and
    return a configured concrete :class:`SourceManager` instance.

    The detection uses each registered manager's ``remotePattern`` so
    new providers light up automatically once they are added to the
    :data:`_SOURCE_MANAGERS` registry above.

    :raises ValueError: If ``remote`` does not match any of the
        registered remote URL patterns.
    """

    for source, factory in _SOURCE_MANAGERS.items():
        candidate = factory(control = control)
        if candidate.remotePattern.match(remote):
            return candidate

    supported = ", ".join(member.value for member in _SOURCE_MANAGERS)
    raise ValueError(
        f"Remote `{remote}` is not supported. "
        f"Supported sources: {supported}"
    )


def get(
    remote : str, name : str, source : Path, destination : Path,
    version : str = "master",
    formatter : Optional[Callable] = lambda : None,
    exists : str = "fail",
    control : Optional[SourceControl] = None
) -> None:
    """
    Thin CLI-side wrapper around :meth:`SourceManager.get` that fetches
    a single extension (``skills`` or ``agents``) from ``remote`` and
    flushes the content into ``destination``. The signature mirrors
    the concrete :meth:`SourceManager._getExtensions` so the CLI does
    not introduce a divergent contract.

    :type  control: Optional[SourceControl]
    :param control: Optional :class:`SourceControl` instance; when
        omitted a default-constructed instance is used. The CLI's
        ``main()`` builds this from ``--pagination`` / ``--token``.
    """

    manager = _resolveManager(
        remote = remote, control = control or SourceControl()
    )

    return manager.get(
        remote = remote, mode = "extensions",
        name = name, source = source, destination = destination,
        version = version, formatter = formatter, exists = exists,
    )


def listExtensions(
    remote : str, library : str, source : Path, version : str = "master",
    control : Optional[SourceControl] = None
) -> list:
    """
    Thin CLI-side wrapper around :meth:`SourceManager.get` (mode set
    to ``list``) that enumerates the immediate child directories of
    ``source`` on the remote at ``version``. Each child directory is
    one extension (skill, agent, etc.) and the returned list is the
    valid universe of ``--name`` values for the ``manager`` command.
    """

    manager = _resolveManager(
        remote = remote, control = control or SourceControl()
    )

    return manager.get(
        remote = remote, mode = "list",
        library = library, source = source, version = version,
    )


def main() -> None:
    """
    Entry point for CLI tool for :mod:`polyskills` that parses the
    command line arguments using :mod:`argparse` module.
    """

    args = buildParser().parse_args()

    # ? terminal commands: 'sources', 'tools' - print and exit early
    # ? these subparsers attach a ``func`` default; manager does not.
    if hasattr(args, "func") and callable(args.func):
        output = args.func()
        if output is not None:
            print(output)
        return None

    # ? dispatch the 'list' subcommand: enumerate extensions and exit
    if args.command == "list":
        source = Path(args.source or f"./{args.library}").as_posix()
        control = SourceControl(
            pagination = args.pagination, token = args.token
        )

        names = listExtensions(
            remote = args.remote, library = args.library,
            source = Path(source), version = args.version,
            control = control,
        )

        header = (
            f"Available {args.library} at "
            f"`{source}` (version = {args.version}):"
        )
        if not names:
            print(header)
            print("\t<no extensions found>")
            return None

        print(header)
        for idx, name in enumerate(names):
            print(f"\t>> {str(idx + 1).zfill(2)}. {name}")
        return None

    # ? set default source, destination directory based on library
    args.source = Path(args.source or f"./{args.library}").as_posix()
    args.destination = Path(
        args.destination or f"./{args.library}/{args.name}"
    )

    # ? dispatch to the concrete remote manager via the wrapper above
    control = SourceControl(
        pagination = args.pagination, token = args.token
    )

    get(
        remote = args.remote, name = args.name,
        source = Path(args.source), destination = args.destination,
        version = args.version, exists = args.exists,
        control = control,
    )

    return None

if __name__ == "__main__":
    sys.exit(main())
