# -*- encoding: utf-8 -*-

"""
Command-Line Interface to Manage LLM Essential Function Code(s)
===============================================================

Module's command-line utility tool to manage essential functions that
are being regularly used by LLM tools for fine control and refine the
content generated by LLM models. The command line is developed using
:mod:`argparse` which is a standard Python package.

.. code-block:: shell

    $ pip install polyskills
    $ polyskills --help # show help documentation

The CLI tool is developed to manage LLM essential functions - like
``SKILLS.md``, ``AGENTS.md`` etc. required to refine the contents.
"""

import sys
import argparse

from polyskills.remote.sources import ValidSources


def buildParser() -> argparse.ArgumentParser:
    """
    Constructs the :func:`argparse.parser` for the :mod:`polyskills`
    CLI tools, that provides sub-parsers with required mutually
    exclusive groups for library management from remote sources.
    """

    parser = argparse.ArgumentParser(
        prog = "polyskills", description = (
            "Manage portable LLM skills hosted on any source controlled "
            "remote repository for LLM tools (like Claude Code, CodeX)."
        )
    )

    subparser = parser.add_subparsers(
        dest = "command", required = True, metavar = "COMMAND"
    )

    # ? Creating Subparsers:: SOURCES - List Available Sources
    sources = subparser.add_parser(
        "sources", help = (
            "List the available (or supported) remote sources, and exit."
        )
    )
    sources.set_defaults(
        func = lambda : "Available Sources:\n" + "\t".join([
            f"\t>> {str(idx + 1).zfill(2)}. {mem.name} - {mem.value}"
            for idx, mem in enumerate(ValidSources)
        ])
    )

    # ? Creating Subparsers:: MANAGE - Manage Remote Library
    manager = subparser.add_parser(
        "manager", help = (
            "Main method to manage skills, agents, etc. from remote "
            "sources, i.e., to fetch and/or update the library "
            "content in different projects or systems. Check "
            "polyskills manage --help for more details."
        )
    )

    manager.add_argument(
        "remote", help = (
            "Remote URL for the Skills Repository, e.g., "
            "https://github.com/<owner>/<repository>"
        )
    )

    return parser


def main() -> None:
    """
    Entry point for CLI tool for :mod:`polyskills` that parses the
    command line arguments using :mod:`argparse` module.
    """

    args = buildParser().parse_args()

    if hasattr(args, "func") and callable(args.func):
        print(args.func())

    return None

if __name__ == "__main__":
    sys.exit(main())
